[Interface]
Address = PLACEHOLDER_CLIENT_ADDRESS
PrivateKey = PLACEHOLDER_PRIVATE_KEY

[Peer]
PublicKey = GH_SEC_WG_PUBLIC_KEY
AllowedIPs = PLACEHOLDER_WG_ALLOWEDIPS
Endpoint = PLACEHOLDER_WG_ENDPOINT
PresharedKey = PLACEHOLDER_PRESHARED_KEY
PersistentKeepalive = 25
